version: "3.5"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ['nodemon', 'index.js']
    volumes:
    - type: bind
      source: .
      target: /home/app
    environment:
    - DB_HOST=postgres
    - DB_USER=postgres
    - DB_NAME=docker-blog
    - DB_PWD=postgres
    container_name: app

  postgres:
    image: postgres:11.2-alpine
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - .:/data2
    environment:
    - POSTGRES_DB=docker-blog
    container_name: db
